services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel
        command:
            -  php-fpm

    webserver:
        image: nginx:alpine
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

    artisan:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - app
            - db
        working_dir: /var/www
        command: >
            sh -c "
              composer install --no-dev --optimize-autoloader &&
              php artisan key:generate &&
              php artisan migrate --seed &&
              php artisan config:clear &&
              php artisan route:clear
            "
        networks:
            - laravel

networks:
    laravel:

volumes:
    db_data:
